// AUTH localstorage keys

export const AUTH_STORAGE_KEY_IDTOKEN = "AUTH_STORAGE_KEY_IDTOKEN";
export const AUTH_STORAGE_KEY_USERID = "AUTH_STORAGE_KEY_USERID";
export const AUTH_STORAGE_KEY_REFRESHTOKEN = "AUTH_STORAGE_KEY_REFRESHTOKEN";
export const AUTH_STORAGE_KEY_EXPIRATIONDATE = "AUTH_STORAGE_KEY_EXPIRATIONDATE";